//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.2 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.11.04 at 09:51:33 PM WAT 
//

@jakarta.xml.bind.annotation.XmlSchema(namespace = "http://com.springbootsoap.allapis", elementFormDefault = jakarta.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.example.tableavailability;
